; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino

lib_extra_dirs = ../../arduino_lib

; upload_port -> upload_ip_com_port.txt   (Fill COM4 for serial upload, IP for OTA upgrade, auto-switch protocol)
extra_scripts = pre:set_upload_port.py

upload_speed = 921600